### ISSUE TITLE
Links in the left column of multi out reverse table are dead.

### ISSUE THREAD

**Issue by Have-a-question-about-this-project** [PoC-Consortium/burstexplorer-tickets#16] opened 2018-07-05 12:53 UTC
https://explore.burst.cryptoguru.org/account/XXXXXXXXXXXXX#

To start off with the "mulitout reverse" table appears when it shouldn't below the "common transactions" table. The same table is shown on the "mulitout reverse" tab. The left column has links to "Page not found".

**Comment by rico666** [comment] 2018-07-09 18:43
duplicate of #14

**Closed as completed by rico666** 2018-07-09 18:43 UTC
Labels: duplicate
